# Generated by Django 4.2.7 on 2024-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя клиента'),
        ),
    ]
