# Generated by Django 4.2.7 on 2024-02-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0002_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berry_name', models.CharField(max_length=30, verbose_name='Ягоды')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Ягода',
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor_name', models.CharField(max_length=30, verbose_name='Декор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Декор',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_level', models.IntegerField(verbose_name='Количество уровней')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Уровень',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_name', models.CharField(max_length=30, verbose_name='Форма')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Форма',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=30, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Топпинг',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'Принят'), ('p', 'Готовится'), ('d', 'Доставляется'), ('c', 'Выполнен')], default='a', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись на торте')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('berry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berries', to='bakecakeapp.berry', verbose_name='Ягоды')),
                ('decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='bakecakeapp.decor', verbose_name='Декор')),
                ('level_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='bakecakeapp.level', verbose_name='Количество уровней')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='bakecakeapp.shape', verbose_name='Форма')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='bakecakeapp.topping', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Торт',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='bakecakeapp.customcake'),
        ),
    ]
