# Generated by Django 4.2.7 on 2024-02-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0003_berry_decor_level_shape_topping_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cake',
            new_name='custom_cake',
        ),
        migrations.RemoveField(
            model_name='order',
            name='compositions',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='CompositionType',
        ),
    ]
