# Generated by Django 4.2.7 on 2024-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0004_rename_cake_order_custom_cake_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customcake',
            options={},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.RemoveField(
            model_name='customcake',
            name='comment',
        ),
    ]
