# Generated by Django 4.2.7 on 2024-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='самовывоз', max_length=200, verbose_name='адрес доставки'),
        ),
    ]
